// src/librarian/__tests__/emitter.test.ts
// CP-T025 — upstream PR test file
//
// Unit tests confirming that the Librarian emits the correct StaffEvents
// at each of its 6 injection points.
//
// Test strategy:
//   - Uses RecordingEmitter (not a mock framework) to capture emit() calls.
//   - Mocks the DB layer (prisma / pg calls) so no live database is required.
//   - Calls setStaffEventEmitter(recorder) before each test.
//   - Calls resetStaffEventEmitter() in afterEach to isolate tests.
//
// The exact import paths, mock structure, and function signatures depend on the
// upstream Iranti TypeScript source. Adjust mocks as needed for the actual source.

import {
  IStaffEventEmitter,
  StaffEventInput,
  NoopEventEmitter,
} from '../../lib/staffEventEmitter';
import {
  setStaffEventEmitter,
  resetStaffEventEmitter,
} from '../../lib/staffEventRegistry';

// ─── RecordingEmitter ─────────────────────────────────────────────────────────
// Captures all emit() calls for assertion. Does not generate eventId/timestamp —
// those are generated by concrete emitter implementations, not by this recorder.

class RecordingEmitter implements IStaffEventEmitter {
  readonly calls: StaffEventInput[] = [];

  emit(event: StaffEventInput): void {
    this.calls.push(event);
  }

  /** Convenience: return the first call, throwing if none. */
  firstCall(): StaffEventInput {
    if (this.calls.length === 0) {
      throw new Error('RecordingEmitter: no calls recorded');
    }
    return this.calls[0];
  }

  /** Convenience: find first call with a given actionType. */
  callOfType(actionType: string): StaffEventInput | undefined {
    return this.calls.find((c) => c.actionType === actionType);
  }
}

// ─── Mocks ────────────────────────────────────────────────────────────────────
// These mocks stub the DB layer. Replace with the actual mock pattern used in
// the Iranti test suite (jest.mock, pg-mem, Prisma mock, etc.).

jest.mock('../../db', () => ({
  prisma: {
    knowledgeEntry: {
      findFirst: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
    },
    archiveEntry: {
      create: jest.fn(),
    },
    idempotencyReceipt: {
      findFirst: jest.fn(),
      create: jest.fn(),
    },
  },
}));

jest.mock('../../lib/lock', () => ({
  withIdentityLock: jest.fn((_key: string, fn: () => Promise<unknown>) => fn()),
}));

jest.mock('fs/promises', () => ({
  writeFile: jest.fn().mockResolvedValue(undefined),
  mkdir: jest.fn().mockResolvedValue(undefined),
}));

// Import the module under test AFTER mocks are set up.
// The exact import path depends on the upstream source structure.
import { librarianWrite } from '../index';
import { prisma } from '../../db';

// ─── Test fixtures ────────────────────────────────────────────────────────────

const baseInput = {
  entityType: 'agent',
  entityId: 'test_agent',
  key: 'preference/language',
  valueRaw: 'TypeScript',
  confidence: 0.85,
  createdBy: 'test_agent',
  source: 'mcp' as const,
  requestId: null,
  validUntil: null,
};

const existingEntry = {
  id: 42,
  entityType: 'agent',
  entityId: 'test_agent',
  key: 'preference/language',
  value: 'JavaScript',
  confidence: 0.60,
  createdBy: 'other_agent',
  source: 'api',
  isProtected: false,
  createdAt: new Date('2026-01-01T00:00:00.000Z'),
};

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('Librarian — emitter injection', () => {
  let recorder: RecordingEmitter;

  beforeEach(() => {
    recorder = new RecordingEmitter();
    setStaffEventEmitter(recorder);
    jest.clearAllMocks();
  });

  afterEach(() => {
    resetStaffEventEmitter();
  });

  // ── write_created ──────────────────────────────────────────────────────────

  it('emits write_created when a new entry is created', async () => {
    // No existing entry → Librarian creates a new one
    (prisma.knowledgeEntry.findFirst as jest.Mock).mockResolvedValue(null);
    (prisma.knowledgeEntry.create as jest.Mock).mockResolvedValue({
      ...baseInput,
      id: 1,
      value: baseInput.valueRaw,
      createdAt: new Date(),
    });
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue(null);

    await librarianWrite(baseInput);

    const event = recorder.callOfType('write_created');
    expect(event).toBeDefined();
    expect(event!.staffComponent).toBe('Librarian');
    expect(event!.actionType).toBe('write_created');
    expect(event!.agentId).toBe(baseInput.createdBy);
    expect(event!.source).toBe(baseInput.source);
    expect(event!.entityType).toBe(baseInput.entityType);
    expect(event!.entityId).toBe(baseInput.entityId);
    expect(event!.key).toBe(baseInput.key);
    expect(event!.level).toBe('audit');
    expect(event!.metadata).toMatchObject({
      confidence: baseInput.confidence,
    });
  });

  // ── write_replaced ─────────────────────────────────────────────────────────

  it('emits write_replaced when an existing entry is superseded', async () => {
    // Existing entry has lower confidence → incoming supersedes it
    (prisma.knowledgeEntry.findFirst as jest.Mock).mockResolvedValue(existingEntry);
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue(null);
    (prisma.knowledgeEntry.update as jest.Mock).mockResolvedValue({
      ...existingEntry,
      value: baseInput.valueRaw,
      confidence: baseInput.confidence,
    });

    await librarianWrite(baseInput);

    const event = recorder.callOfType('write_replaced');
    expect(event).toBeDefined();
    expect(event!.staffComponent).toBe('Librarian');
    expect(event!.actionType).toBe('write_replaced');
    expect(event!.agentId).toBe(baseInput.createdBy);
    expect(event!.entityType).toBe(baseInput.entityType);
    expect(event!.entityId).toBe(baseInput.entityId);
    expect(event!.key).toBe(baseInput.key);
    expect(event!.level).toBe('audit');
    expect(event!.metadata).toMatchObject({
      confidence: baseInput.confidence,
      priorConfidence: existingEntry.confidence,
    });
  });

  // ── write_escalated ────────────────────────────────────────────────────────

  it('emits write_escalated when a conflict cannot be auto-resolved', async () => {
    // Both entries have close confidence → escalation required
    const closeConfidenceEntry = { ...existingEntry, confidence: 0.82 };
    (prisma.knowledgeEntry.findFirst as jest.Mock).mockResolvedValue(closeConfidenceEntry);
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue(null);
    // The fs.writeFile mock already returns undefined (set up in jest.mock above)

    await librarianWrite(baseInput);

    const event = recorder.callOfType('write_escalated');
    expect(event).toBeDefined();
    expect(event!.staffComponent).toBe('Librarian');
    expect(event!.actionType).toBe('write_escalated');
    expect(event!.agentId).toBe(baseInput.createdBy);
    expect(event!.entityType).toBe(baseInput.entityType);
    expect(event!.entityId).toBe(baseInput.entityId);
    expect(event!.key).toBe(baseInput.key);
    expect(event!.level).toBe('audit');
    expect(event!.metadata).toMatchObject({
      conflictReason: 'confidence_conflict',
    });
    // escalationId should be a non-empty string (the escalation filename)
    expect(typeof event!.metadata!.escalationId).toBe('string');
    expect((event!.metadata!.escalationId as string).length).toBeGreaterThan(0);
  });

  // ── write_rejected ─────────────────────────────────────────────────────────

  it('emits write_rejected when the entry is write-protected', async () => {
    const protectedEntry = { ...existingEntry, isProtected: true };
    (prisma.knowledgeEntry.findFirst as jest.Mock).mockResolvedValue(protectedEntry);
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue(null);

    await librarianWrite(baseInput);

    const event = recorder.callOfType('write_rejected');
    expect(event).toBeDefined();
    expect(event!.staffComponent).toBe('Librarian');
    expect(event!.actionType).toBe('write_rejected');
    expect(event!.agentId).toBe(baseInput.createdBy);
    expect(event!.entityType).toBe(baseInput.entityType);
    expect(event!.entityId).toBe(baseInput.entityId);
    expect(event!.key).toBe(baseInput.key);
    expect(event!.level).toBe('audit');
    // reason should describe the rejection cause
    expect(typeof event!.reason).toBe('string');
    expect(event!.reason!.length).toBeGreaterThan(0);
    // metadata should carry the rejectionReason
    expect(event!.metadata).toMatchObject({
      rejectionReason: expect.any(String),
    });
  });

  it('emits write_rejected when incoming confidence is too low to challenge', async () => {
    const highConfidenceEntry = { ...existingEntry, confidence: 0.99 };
    (prisma.knowledgeEntry.findFirst as jest.Mock).mockResolvedValue(highConfidenceEntry);
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue(null);

    // Incoming confidence (0.85) cannot challenge 0.99
    await librarianWrite(baseInput);

    const event = recorder.callOfType('write_rejected');
    expect(event).toBeDefined();
    expect(event!.staffComponent).toBe('Librarian');
    expect(event!.actionType).toBe('write_rejected');
    expect(event!.level).toBe('audit');
  });

  // ── write_deduplicated ─────────────────────────────────────────────────────

  it('emits write_deduplicated on idempotent replay', async () => {
    const inputWithRequestId = { ...baseInput, requestId: 'req-abc-123' };
    // Existing receipt for this requestId
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue({
      requestId: 'req-abc-123',
      entry: { ...existingEntry },
    });

    await librarianWrite(inputWithRequestId);

    const event = recorder.callOfType('write_deduplicated');
    expect(event).toBeDefined();
    expect(event!.staffComponent).toBe('Librarian');
    expect(event!.actionType).toBe('write_deduplicated');
    expect(event!.agentId).toBe(inputWithRequestId.createdBy);
    expect(event!.entityType).toBe(inputWithRequestId.entityType);
    expect(event!.entityId).toBe(inputWithRequestId.entityId);
    expect(event!.key).toBe(inputWithRequestId.key);
    expect(event!.level).toBe('debug');
    expect(event!.metadata).toMatchObject({
      requestId: 'req-abc-123',
    });
  });

  // ── NoopEventEmitter does not throw ───────────────────────────────────────

  it('does not throw when using the default NoopEventEmitter', async () => {
    resetStaffEventEmitter(); // restore no-op
    (prisma.knowledgeEntry.findFirst as jest.Mock).mockResolvedValue(null);
    (prisma.knowledgeEntry.create as jest.Mock).mockResolvedValue({
      ...baseInput,
      id: 2,
      value: baseInput.valueRaw,
      createdAt: new Date(),
    });
    (prisma.idempotencyReceipt.findFirst as jest.Mock).mockResolvedValue(null);

    // Should not throw even though emit() is called internally
    await expect(librarianWrite(baseInput)).resolves.not.toThrow();
  });
});
