// src/lib/staffEventEmitter.ts
// CP-T025 — upstream PR implementation file
//
// Defines the public contract for the Iranti Staff event emitter system.
// All Staff components (Librarian, Attendant, Archivist, Resolutionist) call
// getStaffEventEmitter().emit() at each meaningful decision point.
//
// The default implementation is a zero-overhead no-op, making this change
// fully backward-compatible with all existing deployments.
//
// Consumers who want observability (e.g. the Iranti Control Plane) supply a
// concrete emitter via IrantiConfig.staffEventEmitter at SDK construction time.

import { randomUUID } from 'crypto';

// ─── StaffComponent ────────────────────────────────────────────────────────────

export type StaffComponent =
  | 'Librarian'
  | 'Attendant'
  | 'Archivist'
  | 'Resolutionist';

// ─── EventLevel ───────────────────────────────────────────────────────────────
// 'audit' — operator-facing, always emitted regardless of log verbosity.
// 'debug' — high-frequency or diagnostic events; may be filtered by consumers.

export type EventLevel = 'audit' | 'debug';

// ─── StaffEvent ───────────────────────────────────────────────────────────────
// Full event structure written to the consumer's store (e.g. staff_events table).
// eventId, timestamp, and emittedAt are generated by the emitter, not by callers.
// Callers (Staff components) pass StaffEventInput and let the emitter fill these.

export interface StaffEvent {
  /** UUID v4 — generated by the emitter implementation at emit() time. */
  eventId: string;

  /** ISO 8601 — wall-clock time the event occurred, generated by the emitter. */
  timestamp: string;

  /** Which Staff component produced this event. */
  staffComponent: StaffComponent;

  /**
   * Discriminated action name within the component.
   * Examples: 'write_created', 'handshake_completed', 'entry_archived'.
   */
  actionType: string;

  /**
   * The agent identifier from the originating operation.
   * For Archivist and Resolutionist, this may be 'archivist' or 'operator'.
   */
  agentId: string;

  /**
   * Originating call surface.
   * Expected values: 'mcp' | 'api' | 'claude_code' | 'cli' | 'internal'
   * Note: Attendant events use 'internal' — source is not threaded through
   * AttendantInstance in this PR. Follow-up required.
   */
  source: string;

  /** entityType of the knowledge_base entry involved, if applicable. */
  entityType?: string | null;

  /** entityId of the knowledge_base entry involved, if applicable. */
  entityId?: string | null;

  /** Fact key involved, if applicable. */
  key?: string | null;

  /**
   * Human-readable reason for this event outcome.
   * For write_rejected: the rejection reason string.
   * For write_escalated: the escalation file path summary.
   */
  reason?: string | null;

  /** Event level — controls consumer filtering behaviour. */
  level: EventLevel;

  /**
   * Structured metadata specific to this action type.
   * All fields are optional — consumers must not assume any key is present.
   */
  metadata?: Record<string, unknown> | null;

  /**
   * ISO 8601 — set at the emit() call site, immediately before async delivery.
   * Used for end-to-end latency measurement: emittedAt to deliveredAt.
   * Set to the same value as timestamp in buildStaffEvent().
   */
  emittedAt: string;
}

// ─── StaffEventInput ──────────────────────────────────────────────────────────
// What Staff component callers pass to emit().
// The emitter fills in eventId, timestamp, and emittedAt automatically.
// Callers must supply all other fields.

export type StaffEventInput = Omit<StaffEvent, 'eventId' | 'timestamp' | 'emittedAt'>;

// ─── IStaffEventEmitter ───────────────────────────────────────────────────────
// The interface all Staff components depend on.
//
// Contract for implementors:
//   1. emit() MUST return void immediately — synchronous from the caller's perspective.
//   2. Async delivery (DB write, network I/O) MUST be handled inside emit() via
//      fire-and-forget (e.g. Promise.resolve(...).catch(logError)).
//   3. emit() MUST NOT throw into the caller under any circumstances.
//      All internal errors MUST be caught and logged internally.
//   4. A slow or unavailable backend MUST NOT block or delay Staff operations.

export interface IStaffEventEmitter {
  emit(event: StaffEventInput): void;
}

// ─── NoopEventEmitter ─────────────────────────────────────────────────────────
// Default implementation. Used by all existing deployments that do not configure
// a concrete emitter. emit() is a single empty function body — effectively free
// at V8 JIT steady state (inlineable, no allocations).

export class NoopEventEmitter implements IStaffEventEmitter {
  emit(_event: StaffEventInput): void {
    // Intentionally empty. Zero overhead for deployments without an
    // observability integration. This is the default for all callers
    // that do not pass staffEventEmitter to IrantiConfig.
  }
}

// ─── buildStaffEvent ──────────────────────────────────────────────────────────
// Utility called by concrete emitter implementations to fill in the generated
// fields before persisting or forwarding the event.
//
// Concrete emitters (e.g. DbStaffEventEmitter) call this before the INSERT:
//   const event = buildStaffEvent(input);
//   await pool.query('INSERT INTO staff_events ...', [...eventFields]);
//
// Staff components do NOT call this directly — they call emit(input) and let
// the implementation decide when and how to build the full event.

export function buildStaffEvent(input: StaffEventInput): StaffEvent {
  const now = new Date().toISOString();
  return {
    ...input,
    eventId: randomUUID(),
    timestamp: now,
    emittedAt: now,
  };
}
