#!/usr/bin/env node
/**
 * scripts/package/build-windows.js
 *
 * Produces the Windows NSIS installer for Iranti Control Plane.
 *
 * Steps:
 *   1. Run bundle.js (esbuild CJS pre-bundle)
 *   2. Run build-sea.js (Node SEA binary for Windows x64)
 *   3. Generate the NSIS .nsi script from the template
 *   4. Compile with makensis to produce the final installer .exe
 *
 * Prerequisites (must be installed on the CI runner or build machine):
 *   - NSIS (Nullsoft Scriptable Install System) >= 3.x
 *     Windows: winget install NSIS.NSIS  OR  choco install nsis
 *     The `makensis` binary must be on PATH.
 *
 * Output:
 *   dist/installers/iranti-control-plane-setup-<version>.exe
 *
 * Code signing:
 *   The initial Phase 3 release ships UNSIGNED. SmartScreen will show
 *   "Windows protected your PC" on first run. Users bypass via
 *   "More info" → "Run anyway". Document this in release notes and
 *   the Getting Started screen.
 *   Post-launch upgrade path: OV/EV code signing certificate
 *   (~$200–$700/year from DigiCert or Sectigo).
 *
 * Usage:
 *   node scripts/package/build-windows.js
 */

import { execSync, execFileSync, spawnSync } from 'child_process'
import { mkdirSync, writeFileSync, readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const ROOT = resolve(__dirname, '../../')

// Read version from root package.json
const pkg = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'))
const VERSION = pkg.version ?? '0.0.0'

const DIST_INSTALLERS = resolve(ROOT, 'dist/installers')
const BINARY = resolve(ROOT, 'dist/sea/iranti-cp.exe')
const CLIENT_DIST = resolve(ROOT, 'public/control-plane')
const NSI_PATH = resolve(ROOT, 'dist/iranti-cp-installer.nsi')
const INSTALLER_OUT = resolve(DIST_INSTALLERS, `iranti-control-plane-setup-${VERSION}.exe`)

mkdirSync(DIST_INSTALLERS, { recursive: true })

// ---- Step 1: Bundle ----
console.log('[build-windows] Step 1: esbuild CJS bundle...')
execFileSync(process.execPath, [resolve(__dirname, 'bundle.mjs')], {
  stdio: 'inherit',
  cwd: ROOT,
})

// ---- Step 2: SEA binary ----
console.log('[build-windows] Step 2: Node SEA binary...')
execFileSync(process.execPath, [resolve(__dirname, 'build-sea.mjs')], {
  stdio: 'inherit',
  cwd: ROOT,
})

// ---- Step 3: Generate NSIS script ----
console.log('[build-windows] Step 3: Generating NSIS script...')

const nsiScript = `
; Iranti Control Plane — NSIS Installer Script
; Generated by scripts/package/build-windows.js
; Version: ${VERSION}
;
; Prerequisites for building this installer:
;   NSIS >= 3.x — https://nsis.sourceforge.io/Download
;   Install: winget install NSIS.NSIS  OR  choco install nsis
;
; This installer ships UNSIGNED for the initial Phase 3 release.
; SmartScreen will show "Windows protected your PC" on first run.
; Users bypass: More info → Run anyway.
; See: docs/guides/building-installers.md for the signing upgrade path.

!define APP_NAME "Iranti Control Plane"
!define APP_VERSION "${VERSION}"
!define APP_EXE "iranti-cp.exe"
!define INSTALL_DIR "$PROGRAMFILES64\\Iranti Control Plane"
!define UNINSTALL_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\IrantiControlPlane"

Name "\${APP_NAME}"
OutFile "${INSTALLER_OUT.replace(/\\/g, '\\\\')}"
InstallDir "\${INSTALL_DIR}"
InstallDirRegKey HKLM "\${UNINSTALL_KEY}" "InstallLocation"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

; Modern UI
!include "MUI2.nsh"
!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "\${INSTALL_DIR}"

  ; Copy the SEA binary
  File "${BINARY.replace(/\\/g, '\\\\')}"

  ; Copy the frontend static assets (sidecar directory)
  SetOutPath "\${INSTALL_DIR}\\public\\control-plane"
  File /r "${CLIENT_DIST.replace(/\\/g, '\\\\')}\\*.*"

  ; Copy package.json for version detection at runtime
  SetOutPath "\${INSTALL_DIR}"
  File "${resolve(ROOT, 'package.json').replace(/\\/g, '\\\\')}"

  ; Create Start Menu shortcut
  CreateDirectory "$SMPROGRAMS\\Iranti Control Plane"
  CreateShortcut "$SMPROGRAMS\\Iranti Control Plane\\Iranti Control Plane.lnk" "\${INSTALL_DIR}\\\${APP_EXE}"
  CreateShortcut "$SMPROGRAMS\\Iranti Control Plane\\Uninstall.lnk" "\${INSTALL_DIR}\\Uninstall.exe"

  ; Register uninstaller in Add/Remove Programs
  WriteRegStr HKLM "\${UNINSTALL_KEY}" "DisplayName" "\${APP_NAME}"
  WriteRegStr HKLM "\${UNINSTALL_KEY}" "DisplayVersion" "\${APP_VERSION}"
  WriteRegStr HKLM "\${UNINSTALL_KEY}" "InstallLocation" "\${INSTALL_DIR}"
  WriteRegStr HKLM "\${UNINSTALL_KEY}" "UninstallString" "\${INSTALL_DIR}\\Uninstall.exe"
  WriteRegDWORD HKLM "\${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKLM "\${UNINSTALL_KEY}" "NoRepair" 1

  ; Write the uninstaller
  WriteUninstaller "\${INSTALL_DIR}\\Uninstall.exe"

  ; Optional: add to Windows startup (checkbox in a real installer — simplified here)
  ; Uncomment to enable auto-launch on login:
  ; WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "IrantiControlPlane" "\${INSTALL_DIR}\\\${APP_EXE}"
SectionEnd

Section "Uninstall"
  ; Remove installed files
  Delete "\${INSTALL_DIR}\\\${APP_EXE}"
  Delete "\${INSTALL_DIR}\\package.json"
  Delete "\${INSTALL_DIR}\\Uninstall.exe"
  RMDir /r "\${INSTALL_DIR}\\public"

  ; Remove Start Menu entries
  Delete "$SMPROGRAMS\\Iranti Control Plane\\Iranti Control Plane.lnk"
  Delete "$SMPROGRAMS\\Iranti Control Plane\\Uninstall.lnk"
  RMDir "$SMPROGRAMS\\Iranti Control Plane"

  ; Remove installation directory (only if empty after above)
  RMDir "\${INSTALL_DIR}"

  ; Remove registry entries
  DeleteRegKey HKLM "\${UNINSTALL_KEY}"
  DeleteRegValue HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "IrantiControlPlane"
SectionEnd
`.trim()

writeFileSync(NSI_PATH, nsiScript, 'utf8')
console.log('[build-windows] NSIS script written to:', NSI_PATH)

// ---- Step 4: Compile with makensis ----
console.log('[build-windows] Step 4: Compiling with makensis...')
console.log('[build-windows] Output:', INSTALLER_OUT)

// Check makensis is available
const checkMakensis = spawnSync('makensis', ['/VERSION'], { shell: true })
if (checkMakensis.error || checkMakensis.status !== 0) {
  console.error('[build-windows] makensis not found on PATH.')
  console.error('[build-windows] Install NSIS and ensure makensis is on PATH:')
  console.error('[build-windows]   winget install NSIS.NSIS')
  console.error('[build-windows]   choco install nsis')
  process.exit(1)
}

try {
  execSync(`makensis "${NSI_PATH}"`, { stdio: 'inherit', cwd: ROOT })
  console.log('[build-windows] Installer built successfully:', INSTALLER_OUT)
} catch (err) {
  console.error('[build-windows] makensis failed:', err.message)
  process.exit(1)
}
