-- Migration: 001_create_staff_events
-- Spec ref: CP-T001 §3 (Option 1 schema)
-- Creates the staff_events table for the Iranti Control Plane event stream.
--
-- The `event_id` column name matches CP-T001 spec (not generic `id`).
-- CHECK constraints on staff_component and level enforce data integrity.
-- All INSERT statements from application code use parameterized queries only.

CREATE TABLE IF NOT EXISTS staff_events (
  -- Primary key: UUID generated by DB
  event_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Timestamp: when the event occurred (NOT NULL — every event must have a timestamp)
  timestamp       TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Staff component: which subsystem emitted this event
  -- Constrained to the 4 known components for data integrity
  staff_component VARCHAR(32) NOT NULL
    CHECK (staff_component IN ('Librarian', 'Attendant', 'Archivist', 'Resolutionist')),

  -- Action type: what happened within the component
  action_type     VARCHAR(64) NOT NULL,

  -- The agent whose operation triggered this event
  agent_id        TEXT,       -- Nullable: may be unknown for adapter-inferred events

  -- The source surface (mcp, api, cli, etc.)
  source          TEXT,

  -- Entity targeting fields (all nullable — not all events target an entity)
  entity_type     TEXT,
  entity_id       TEXT,
  key             TEXT,

  -- Human-readable note from the triggering operation
  reason          TEXT,

  -- Event level: audit (always on) or debug (configurable)
  level           VARCHAR(16) NOT NULL DEFAULT 'audit'
    CHECK (level IN ('audit', 'debug')),

  -- Component-specific supplementary data (schema varies by actionType)
  metadata        JSONB
);

-- Index 1: Primary query pattern — time-ordered event stream
-- Supports: SELECT * FROM staff_events ORDER BY timestamp DESC
-- Supports: SELECT * FROM staff_events WHERE timestamp > :cursor ORDER BY timestamp ASC
CREATE INDEX IF NOT EXISTS idx_staff_events_timestamp ON staff_events (timestamp DESC);

-- Index 2: Filter by Staff component
-- Supports: WHERE staff_component = 'Librarian'
CREATE INDEX IF NOT EXISTS idx_staff_events_component ON staff_events (staff_component);

-- Index 3: Filter by entity (compound — covers both type+id and type-only queries)
-- Supports: WHERE entity_type = 'ticket' AND entity_id = 'cp_t001'
-- Supports: WHERE entity_type = 'ticket'
CREATE INDEX IF NOT EXISTS idx_staff_events_entity ON staff_events (entity_type, entity_id);

-- Index 4: Filter by level (most queries filter to level='audit')
CREATE INDEX IF NOT EXISTS idx_staff_events_level ON staff_events (level);

-- Index 5: Filter by agent
-- Supports: WHERE agent_id = 'product_manager'
CREATE INDEX IF NOT EXISTS idx_staff_events_agent ON staff_events (agent_id);
